# Generated by Django 3.1.2 on 2020-11-09 13:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentID', models.IntegerField(primary_key=True, serialize=False)),
                ('menuItemID', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('commentfName', models.CharField(max_length=100)),
                ('commentlName', models.CharField(max_length=100)),
                ('commentContent', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsertCustomer',
            fields=[
                ('customerID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('authID', models.IntegerField()),
                ('phoneNo', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='InsertOrder',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('teamID', models.IntegerField()),
                ('customerID', models.IntegerField()),
                ('cateringDatetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('CustFirstName', models.CharField(max_length=255)),
                ('custLastName', models.CharField(max_length=255)),
                ('custEmail', models.CharField(max_length=50)),
                ('custContact', models.CharField(max_length=20)),
                ('custOrder', models.CharField(max_length=255)),
                ('custRequest', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('amountDue', models.IntegerField(default='50')),
                ('Status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cateringorder',
            },
        ),
        migrations.CreateModel(
            name='InsertStock',
            fields=[
                ('stockID', models.IntegerField(primary_key=True, serialize=False)),
                ('stockName', models.CharField(max_length=100)),
                ('amountLeft', models.IntegerField()),
                ('deficit', models.IntegerField()),
                ('menuItemID', models.IntegerField()),
            ],
            options={
                'db_table': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('menuItemID', models.IntegerField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=100)),
                ('itemPrice', models.IntegerField()),
            ],
            options={
                'db_table': 'menuitem',
            },
        ),
        migrations.CreateModel(
            name='StaffTable',
            fields=[
                ('staffID', models.IntegerField(primary_key=True, serialize=False)),
                ('teamID', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='StaffTeam',
            fields=[
                ('teamID', models.IntegerField(primary_key=True, serialize=False)),
                ('dateFormed', models.DateField()),
                ('dateDisbanded', models.DateField()),
            ],
            options={
                'db_table': 'staffteam',
            },
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
    ]
