# Generated by Django 3.1.2 on 2020-10-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201014_1422'),
        ('accounts', '0002_auto_20201012_1629'),
    ]

    operations = [
    ]
