# Generated by Django 3.1.2 on 2020-10-19 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_merge_20201015_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsertCustomer',
            fields=[
                ('customerID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('authID', models.IntegerField()),
                ('phoneNo', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.RenameField(
            model_name='insertorder',
            old_name='CustFirstName',
            new_name='custFirstName',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
